In [259]:
# ISLP has already been installed.

import numpy as np
from sklearn import svm
import sklearn.model_selection as model_selection
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from ISLP import load_data

# Loading the dataset
data_set = load_data('Khan')


# Extracting the dataframes from the given dictionary
x_train_df = data_set['xtrain']
x_test_df = data_set['xtest']
y_train_df = data_set['ytrain']
y_test_df = data_set['ytest']

# Converting the dataframes into matrices for convenient processing
Matrix_xtrain = x_train_df.to_numpy()
Matrix_xtest = x_test_df.to_numpy()

Matrix_ytrain = y_train_df.to_numpy()
Matrix_ytest = y_test_df.to_numpy()

# Defining the kernel functions 
lin = svm.SVC(kernel='linear', C=20).fit(Matrix_xtrain, Matrix_ytrain)
poly = svm.SVC(kernel='poly', C=20).fit(Matrix_xtrain, Matrix_ytrain)
rbf = svm.SVC(kernel='rbf', C=20).fit(Matrix_xtrain, Matrix_ytrain)
sig = svm.SVC(kernel='sigmoid', C=20).fit(Matrix_xtrain, Matrix_ytrain)

# Testing predictability
poly_pred = poly.predict(Matrix_xtest)
rbf_pred = rbf.predict(Matrix_xtest)
sig_pred = sig.predict(Matrix_xtest)
lin_pred = lin.predict(Matrix_xtest)

# Calculating the F1 score and the accuracy

# Linear kernel
lin_accuracy = accuracy_score(Matrix_ytest, lin_pred)
lin_f1 = f1_score(Matrix_ytest, lin_pred, average='weighted')
print('Accuracy (Linear Kernel): ', "%.2f" % (lin_accuracy*100), '%')
print('F1 (Linear Kernel): ', "%.2f" % (lin_f1*100), '%')
print()

# Polynomial kernel
poly_accuracy = accuracy_score(Matrix_ytest, poly_pred)
poly_f1 = f1_score(Matrix_ytest, poly_pred, average='weighted')
print('Accuracy (Polynomial Kernel): ', "%.2f" % (poly_accuracy*100), '%')
print('F1 (Polynomial Kernel): ', "%.2f" % (poly_f1*100), '%')

print()

# Radial basis function (RBF) kernel
rbf_accuracy = accuracy_score(Matrix_ytest, rbf_pred)
rbf_f1 = f1_score(Matrix_ytest, rbf_pred, average='weighted')
print('Accuracy (RBF Kernel): ', "%.2f" % (rbf_accuracy*100), '%')
print('F1 (RBF Kernel): ', "%.2f" % (rbf_f1*100), '%')

print()

# Signmoid kernel 
sig_accuracy = accuracy_score(Matrix_ytest, sig_pred)
sig_f1 = f1_score(Matrix_ytest, sig_pred, average='weighted')
print('Accuracy (Sigmoid Kernel): ', "%.2f" % (sig_accuracy*100), '%')
print('F1 (Sigmoid Kernel): ', "%.2f" % (sig_f1*100), '%')

Accuracy (Linear Kernel):  90.00 %
F1 (Linear Kernel):  89.71 %

Accuracy (Polynomial Kernel):  90.00 %
F1 (Polynomial Kernel):  89.71 %

Accuracy (RBF Kernel):  80.00 %
F1 (RBF Kernel):  76.73 %

Accuracy (Sigmoid Kernel):  85.00 %
F1 (Sigmoid Kernel):  85.08 %


## Sample problem; Iris data set with 3 classes

In [251]:
import numpy as np


iris = datasets.load_iris()

x = iris.data[:]
y = iris.target

# Creating the training-test split
X_train, X_test, y_train, y_test = model_selection.train_test_split(x, y, train_size=0.80, test_size=0.20, random_state=101)

print(np.shape(X_train))
print(X_train)
print()
# Defining the kernel functions 
rbf = svm.SVC(kernel='rbf', gamma=0.5, C=1).fit(X_train, y_train)
poly = svm.SVC(kernel='poly', degree=3, C=1).fit(X_train, y_train)

# Testing predictability
poly_pred = poly.predict(X_test)
rbf_pred = rbf.predict(X_test)

poly_accuracy = accuracy_score(y_test, poly_pred)
poly_f1 = f1_score(y_test, poly_pred, average='weighted')
print('Accuracy (Polynomial Kernel): ', "%.2f" % (poly_accuracy*100))
print('F1 (Polynomial Kernel): ', "%.2f" % (poly_f1*100))


rbf_accuracy = accuracy_score(y_test, rbf_pred)
rbf_f1 = f1_score(y_test, rbf_pred, average='weighted')
print('Accuracy (RBF Kernel): ', "%.2f" % (rbf_accuracy*100))
print('F1 (RBF Kernel): ', "%.2f" % (rbf_f1*100))

print(poly_pred)
print(y_test)

(120, 4)
[[6.5 3.  5.8 2.2]
 [5.5 2.5 4.  1.3]
 [6.5 3.  5.5 1.8]
 [5.8 2.7 3.9 1.2]
 [6.8 3.  5.5 2.1]
 [5.7 2.8 4.5 1.3]
 [6.7 3.1 4.7 1.5]
 [5.9 3.  4.2 1.5]
 [5.6 2.7 4.2 1.3]
 [7.7 3.  6.1 2.3]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.6 0.2]
 [6.7 3.  5.  1.7]
 [5.6 3.  4.5 1.5]
 [4.3 3.  1.1 0.1]
 [7.1 3.  5.9 2.1]
 [5.8 2.7 4.1 1. ]
 [4.9 3.1 1.5 0.2]
 [5.1 2.5 3.  1.1]
 [5.6 2.5 3.9 1.1]
 [5.1 3.3 1.7 0.5]
 [5.8 2.7 5.1 1.9]
 [5.  3.6 1.4 0.2]
 [4.9 2.4 3.3 1. ]
 [6.7 2.5 5.8 1.8]
 [5.8 2.6 4.  1.2]
 [4.9 3.6 1.4 0.1]
 [5.1 3.4 1.5 0.2]
 [6.1 3.  4.6 1.4]
 [4.6 3.4 1.4 0.3]
 [6.4 3.2 4.5 1.5]
 [7.7 2.6 6.9 2.3]
 [6.3 3.4 5.6 2.4]
 [5.4 3.  4.5 1.5]
 [5.8 4.  1.2 0.2]
 [6.  2.9 4.5 1.5]
 [4.6 3.1 1.5 0.2]
 [5.8 2.7 5.1 1.9]
 [6.9 3.2 5.7 2.3]
 [6.  3.4 4.5 1.6]
 [6.2 3.4 5.4 2.3]
 [6.6 2.9 4.6 1.3]
 [6.3 3.3 6.  2.5]
 [4.7 3.2 1.3 0.2]
 [4.8 3.  1.4 0.3]
 [4.9 3.1 1.5 0.1]
 [6.5 2.8 4.6 1.5]
 [4.6 3.2 1.4 0.2]
 [5.1 3.8 1.6 0.2]
 [5.  3.4 1.6 0.4]
 [7.4 2.8 6.1 1.9]
 [5